services:
  app:
    image: sparql-conformance-uploader
    build:
      context: .
    container_name: sparql-conformance-uploader
    ports:
      - "PORT:3000"
    volumes:
      - PATH:/results            # Mount the results directory
      - PATH:/keys               # Mount the keys directory (place github and server key in the directory)
      - PATH:/config.json    # Mount config directory for editing
